import Book from '../src/components/Book';
import { HomeMain } from '../src/styles/homepage';
import Head from 'next/head';

const Home = ({ booksList }) => {
  return (
    <>
    <Head>
        <title>Bibbble</title>
        <meta name="Breno Rosado" content="Generated by create next app" />
        <link rel="icon" href="/logo_Bibbble.ico" />
      </Head>
      <HomeMain>
        <section>
          {
            booksList.map(item => <Book data={item}/>)
          }
        </section>
      </HomeMain>
    </>
  )
};

export const getServerSideProps = async () => {
  const res = await fetch('https://fakerapi.it/api/v1/books');
  const booksList = await res.json();

  return {
    props: {
      booksList: booksList.data
    }
  };
};

export default Home;